root = "."
tmp_dir = "tmp"

[build]
  cmd = "$HOME/go/bin/templ generate && go build -o ./tmp/recipebox ."
  entrypoint = ["./tmp/recipebox", "serve"]
  include_ext = ["go", "templ", "sql", "yaml"]
  exclude_dir = ["tmp", "bin", "docs", "site", ".venv", ".git"]
  exclude_regex = ["_templ\\.go$"]
  delay = 1000

[log]
  main_only = true
